browser_instance_getter gets args from request object
pytest-dev/pytest-splinter pull request #122
Opened 2019-04-03 20:48 UTC by jsfehler

This PR changes the functions nested inside browser_instance_getter to receive the request object and pull fixture values directly, instead of passing the fixture values in from browser_instance_getter.

The reason for this is because passing the fixture values from browser_instance_getter forces them to always be session scoped. Since browser_instance_getter is session scoped, the fixtures are only accessed once. Accessing the request object allows the fixtures to be function scoped.

The main reason for this change is the necessity to have `splinter_driver_kwargs` set on a per-test basis.

ie:

The following now works:
```
@pytest.fixture(scope="function")
def splinter_driver_kwargs(request):
    return {
        'name': request.node.name,
    },
```

2019-04-14 13:36 UTC, youtux commented on pytest_splinter/plugin.py
> +def get_args(request):
I'd keep get_args independent from knowing how to access fixtures from a request. Please keep the old signature

2019-04-14 13:38 UTC, youtux commented on tests/test_plugin.py
> +def test_executable(testdir, request):
We are not testing the real behaviour that we expect: given there are 2 tests, and some parametrization of the webdriver depends on the current test being run, then the browser  should be started 2 times with the expected 2 different parameterizations.

2020-09-11 18:29 UTC, bubenkoff commented
@jsfehler please make requested changes and resolve conflicts

2020-09-11 18:48 UTC, bubenkoff requested changes
@jsfehler please make requested changes and resolve conflicts

2022-08-07 08:55 UTC, mpasternak commented
Hello @jsfehler ! As we have running CI again, could you please remove conflicts and re-submit the code? Thanks

2022-08-08 21:34 UTC, mpasternak commented
3 years without contact with the original submitter, closing as inactive. In case anybody feels this was wrong thing to do please comment and I will reopen. Thanks.

2022-08-08 21:34 UTC, closed without merging