Simplify --splinter-headless
pytest-dev/pytest-splinter pull request #123
Opened 2019-05-13 14:12 UTC by tony

It feels a bit strange doing true/false for a headless option.
It could be my own aesthetic / tastes.

`argparse` has `'store_true'` for cases like this (see [docs](https://docs.python.org/3/library/argparse.html#action)):

> 'store_true' and 'store_false' - These are special cases of 'store_const' used for storing the values True and False respectively. In addition, they create default values of `False` and `True` respectively..

So `--headless` sets it to `True`.

I can't think of a case where a user would want to accept False considering the default behavior is that, but if they did, they can always add their own option via `pytest_addoption`)

Not entering --splinter-headless infers False (this is backed by default values in pytest-splinter and probably user intuition). Entering --headless implies the user wants to run in headless mode.

2019-05-14 13:44 UTC, youtux commented
Sorry @bubenkoff, I don't have time to check this and the possible incompatibilities that may arise.

2019-05-14 14:37 UTC, tony commented
@youtux @bubenkoff 

I doubt there's a side effect.

Here's two examples of `--headless` being used as in this PR: https://github.com/seleniumbase/SeleniumBase/blob/v1.23.9/seleniumbase/plugins/selenium_plugin.py#L87, https://github.com/pytest-dev/pytest-selenium/issues/135#issuecomment-368308663

As for this project in particular:

pytest-splinter defaults to False for headless (as a user would probably expect)

It's really unintuitive to pass true/false to an option when the default behavior is false.

There are corner cases (as always), but nothing is stopping them from writing their own option (e.g. `--no-headless`) or customizing the `splinter_headless` fixture in their conftest. We could also introduce `--no-headless` at a later time, but it's doubtful a request would arise.

2019-05-31 16:09 UTC, tony commented
@youtux @bubenkoff 

This is behavior splinter should use by default.  I think we should merge this.

There's no point in `--splinter-headless false` because `splinter_headless` option already defaults to false.

2019-07-20 22:51 UTC, tony commented
Hi @youtux @bubenkoff, checking in, just rebased.

The reason I stand behind this is it's simpler. 

Omission of the flag generally implies falsiness. Going by the https://en.wikipedia.org/wiki/Principle_of_least_astonishment.

There's no point in `--splinter-headless`  accepting false if `splinter_headless` defaults to `False`.

At this point I already written my own `--headless` to get the equivalent behavior. It just is a bit odd to have a flag set to false when it defaults to false :laughing: 

If it's not okay to put in it's okay to close this.

2020-09-11 18:47 UTC, bubenkoff requested changes
@tony please resolve conflicts

2020-09-11 21:50 UTC, tony commented
@bubenkoff Doing so now.

2020-09-11 21:57 UTC, tony commented
@bubenkoff Done

2020-09-11 21:59 UTC, bubenkoff requested changes
please:
- fix the documentation
- add changelog record
- add authors record

2020-09-12 18:17 UTC, tony commented
@bubenkoff Better now?

2020-09-12 21:21 UTC, bubenkoff approved these changes

2020-09-12 21:22 UTC, bubenkoff commented
please squash & merge

2020-09-12 21:23 UTC, merged