Add support for pytest-xdist 2.1.0
pytest-dev/pytest-splinter pull request #151
Opened 2020-09-11 17:46 UTC by jsfehler

2020-09-11 18:27 UTC, bubenkoff commented
same comments about the changelog - please follow the flow

2020-09-11 18:45 UTC, bubenkoff requested changes
same comments about the changelog - please follow the flow

2020-09-25 18:22 UTC, jsfehler commented
@bubenkoff Changes made.

2020-09-26 06:45 UTC, bubenkoff requested changes

2020-09-26 06:45 UTC, bubenkoff commented on setup.py
> +        'xdist': ['pytest-xdist>=2.1.0'],
please reflect this in the test requirements then, as apparently it was installing the older version or why is it not catching the incompatibility ATM?

2022-01-08 22:39 UTC, closed without merging