Fix --splinter-headless, as it could as well be of type bool, not str.
pytest-dev/pytest-splinter pull request #154
Opened 2020-12-24 21:42 UTC by mpasternak

Thank you for helping with getting my previous suggestions included in the main branch, also thank you for releasing the package on PyPI. 

I have tested 3.3.0 and it won't work as documented, unless you create this small patch. 

Also please note I have not tested other cases when a ``splinter_*`` variable is compared to a string ``"true"``, but they could be as well dysfunctional.

2020-12-24 23:58 UTC, bubenkoff requested changes
doesn't the splinter_headless option have the boolean type?
it really feels wrong to check for the true value like that

2020-12-25 00:39 UTC, mpasternak commented
> doesn't the splinter_headless option have the boolean type?
> it really feels wrong to check for the true value like that

Of course it does. 

My thinking is... this has worked for some time. So perhaps some other component of the stack (maybe pytest itself) made passing those variables as strings. So if my theory is true, then perhaps people importing from older versions of pytest would get problems if I checked only for bool not str. 

If not, this value is bool as per pytest 6.2.1 and pytest-splinter 3.3.0

BUT on the other hand, as this is done via options parser and the option has "store_true" value, this is not possible for this option to be anything else than a boolean. 

Branch updated.

2020-12-25 00:46 UTC, bubenkoff requested changes
Still, not a solution for me,
please remove the comparison with True, this is not a good style at all.

We need to fix the actual issue, which is the declaration of the boolean options in the plugin.py, those are simply wrong:

group.addoption(
        "--splinter-headless",
        help="Run the browser in headless mode.",
        action="store_true",
        dest="splinter_headless",
        default="false",
    )

there's no explicit type, also the default is a string!
we also need to fix other boolean options
so please spend a little bit more time but let's fix it properly

2020-12-25 01:08 UTC, mpasternak commented
I checked how other options are added with .add_option and they should be fine, looking from they way they're initiated. They have string values. Also... I don't even know what they do and I don't have means to test those -- I'm not touching them. 

As per splinter_headless, looks like it should be fine after my last change

2020-12-25 02:48 UTC, bubenkoff approved these changes
ok makes sense, thanks

2020-12-25 02:49 UTC, bubenkoff requested changes
forgot to mention: please add changelog entry

2020-12-25 19:24 UTC, bubenkoff approved these changes

2020-12-25 19:26 UTC, merged

2020-12-25 19:35 UTC, bubenkoff commented
thanks 3.3.1 is out

2020-12-25 19:35 UTC, mpasternak commented
thank you